default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: trabalho_restful_development

test:
  <<: *default
  database: trabalho_restful_test

production:
  <<: *default
  database: trabalho_restful_production
